name: project_management
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.5.3+2
  lottie: ^1.4.0
  firebase_auth: ^3.6.4
  firebase_core: ^1.21.0
  cloud_firestore: ^3.1.18
  http: ^0.13.4
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

